# Generated by Django 4.1 on 2022-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstdate', models.DateField()),
                ('seconddate', models.DateField()),
            ],
        ),
    ]
